#!/usr/bin/env python3
"""
Fix all incorrect image field names in country data
"""

import json

def fix_all_image_fields():
    """Fix all incorrect image field names"""
    print("🔧 Fixing all incorrect image field names...")
    
    # Load country data
    with open('countries_data.json', 'r', encoding='utf-8') as f:
        countries_data = json.load(f)
    
    # Complete ISO mapping for all countries
    iso_mapping = {
        'Egypt': 'eg.png',
        'India': 'in.png',
        'Vatican City': 'va.png',
        'North Macedonia': 'mk.png',
        'Tunisia': 'tn.png',
        'Niger': 'ne.png',
        'Iraq': 'iq.png',
        'Morocco': 'ma.png',
        'Switzerland': 'ch.png',
        'South Africa': 'za.png',
        'Israel': 'il.png',
        'Libya': 'ly.png',
        'Bangladesh': 'bd.png',
        'San Marino': 'sm.png',
        'Uruguay': 'uy.png',
        'Papua New Guinea': 'pg.png',
        'Cape Verde': 'cv.png',
        'Estonia': 'ee.png',
        'Saudi Arabia': 'sa.png',
        'Belize': 'bz.png',
        'Benin': 'bj.png',
        'Luxembourg': 'lu.png',
        'New Zealand': 'nz.png',
        'Kuwait': 'kw.png',
        'Syria': 'sy.png',
        'Algeria': 'dz.png',
        'Mali': 'ml.png',
        'Cyprus': 'cy.png',
        'Australia': 'au.png',
        'France': 'fr.png',
        'Vietnam': 'vn.png',
        'Serbia': 'rs.png',
        'Ukraine': 'ua.png',
        'Antigua and Barbuda': 'ag.png',
        'Denmark': 'dk.png',
        'Italy': 'it.png',
        'Cambodia': 'kh.png',
        'Equatorial Guinea': 'gq.png',
        'Iceland': 'is.png',
        'Georgia': 'ge.png',
        'Lesotho': 'ls.png',
        'Russia': 'ru.png',
        'Bahrain': 'bh.png',
        'Barbados': 'bb.png',
        'Dominica': 'dm.png',
        'Indonesia': 'id.png',
        'Bahamas': 'bs.png',
        'Romania': 'ro.png',
        'Canada': 'ca.png',
        'Saint Kitts and Nevis': 'kn.png',
        'Togo': 'tg.png',
        'Turkey': 'tr.png',
        'Tajikistan': 'tj.png',
        'Mauritania': 'mr.png',
        'Pakistan': 'pk.png',
        'Colombia': 'co.png',
        'Sao Tome and Principe': 'st.png',
        'Peru': 'pe.png',
        'Sri Lanka': 'lk.png',
        'Costa Rica': 'cr.png',
        'Gambia': 'gm.png',
        'Ecuador': 'ec.png',
        'Netherlands': 'nl.png',
        'Albania': 'al.png',
        'Jamaica': 'jm.png',
        'Honduras': 'hn.png',
        'Vanuatu': 'vu.png',
        'Mongolia': 'mn.png',
        'Slovakia': 'sk.png',
        'Ethiopia': 'et.png',
        'Iran': 'ir.png',
        'Belgium': 'be.png',
        'Malawi': 'mw.png',
        'Oman': 'om.png',
        'Chad': 'td.png',
        'Jordan': 'jo.png',
        'Suriname': 'sr.png',
        'Guatemala': 'gt.png',
        'Namibia': 'na.png',
        'Grenada': 'gd.png',
        'East Timor': 'tl.png',
        'Croatia': 'hr.png',
        'Tanzania': 'tz.png',
        'Spain': 'es.png',
        'Uzbekistan': 'uz.png',
        'Samoa': 'ws.png',
        'Angola': 'ao.png',
        'Monaco': 'mc.png',
        'Maldives': 'mv.png',
        'Brunei': 'bn.png',
        'El Salvador': 'sv.png',
        'Uganda': 'ug.png',
        'Saint Vincent and the Grenadines': 'vc.png',
        'Kazakhstan': 'kz.png',
        'Trinidad and Tobago': 'tt.png',
        'Taiwan': 'tw.png',
        'Laos': 'la.png',
        'Liechtenstein': 'li.png',
        'South Sudan': 'ss.png',
        'Bulgaria': 'bg.png',
        'Haiti': 'ht.png',
        'Malta': 'mt.png',
        'Nicaragua': 'ni.png',
        'Djibouti': 'dj.png',
        'Germany': 'de.png',
        'South Korea': 'kr.png',
        'Kiribati': 'ki.png',
        'Yemen': 'ye.png',
        'Tonga': 'to.png',
        'Guinea': 'gn.png',
        'Madagascar': 'mg.png',
        'Zambia': 'zm.png',
        'Norway': 'no.png',
        'Liberia': 'lr.png',
        'Eswatini': 'sz.png',
        'Central African Republic': 'cf.png',
        'Andorra': 'ad.png',
        'Belarus': 'by.png',
        'Montenegro': 'me.png',
        'Senegal': 'sn.png',
        'United Kingdom': 'gb.png',
        'North Korea': 'kp.png',
        'Lebanon': 'lb.png',
        'Gabon': 'ga.png',
        'Palau': 'pw.png',
        'Portugal': 'pt.png',
        'Moldova': 'md.png',
        'Dominican Republic': 'do.png',
        'Hungary': 'hu.png',
        'Nepal': 'np.png',
        'Poland': 'pl.png',
        'Latvia': 'lv.png',
        'Mozambique': 'mz.png',
        'Brazil': 'br.png',
        'Zimbabwe': 'zw.png',
        'Ghana': 'gh.png',
        'Rwanda': 'rw.png',
        'Finland': 'fi.png',
        'Singapore': 'sg.png',
        'Solomon Islands': 'sb.png',
        'Fiji': 'fj.png',
        'Argentina': 'ar.png',
        'Bhutan': 'bt.png',
        'Somalia': 'so.png',
        'Seychelles': 'sc.png',
        'United Arab Emirates': 'ae.png',
        'Mexico': 'mx.png',
        'Sudan': 'sd.png',
        'United States': 'us.png',
        'Congo': 'cg.png',
        'Qatar': 'qa.png',
        'Azerbaijan': 'az.png',
        'Democratic Republic of the Congo': 'cd.png',
        'Panama': 'pa.png',
        'Ivory Coast': 'ci.png',
        'Lithuania': 'lt.png',
        'Greece': 'gr.png',
        'Kyrgyzstan': 'kg.png',
        'Bosnia and Herzegovina': 'ba.png',
        'Paraguay': 'py.png',
        'Thailand': 'th.png',
        'Austria': 'at.png',
        'Eritrea': 'er.png',
        'Ireland': 'ie.png',
        'Nauru': 'nr.png',
        'Sweden': 'se.png',
        'Cameroon': 'cm.png',
        'Philippines': 'ph.png',
        'Chile': 'cl.png',
        'Guyana': 'gy.png',
        'Slovenia': 'si.png',
        'Kenya': 'ke.png',
        'Saint Lucia': 'lc.png',
        'Turkmenistan': 'tm.png',
        'Comoros': 'km.png',
        'Botswana': 'bw.png',
        'Czech Republic': 'cz.png',
        'Venezuela': 've.png',
        'Sierra Leone': 'sl.png',
        'Guinea-Bissau': 'gw.png',
        'Burundi': 'bi.png',
        'Bolivia': 'bo.png',
        'Cuba': 'cu.png',
        'Malaysia': 'my.png',
        'Afghanistan': 'af.png',
        'China': 'cn.png',
        'Japan': 'jp.png',
        'Burkina Faso': 'bf.png',
        'Armenia': 'am.png',
        'Myanmar': 'mm.png',
        'Mauritius': 'mu.png'
    }
    
    fixed_count = 0
    for country in countries_data:
        country_name = country['name']
        
        # Remove incorrect image_file field if it exists
        if 'image_file' in country:
            del country['image_file']
            print(f"✓ Removed incorrect 'image_file' for {country_name}")
        
        # Set correct imageFile if we have a mapping
        if country_name in iso_mapping:
            correct_image = iso_mapping[country_name]
            country['imageFile'] = correct_image
            print(f"✓ Fixed {country_name}: {correct_image}")
            fixed_count += 1
    
    # Save updated data
    with open('countries_data.json', 'w', encoding='utf-8') as f:
        json.dump(countries_data, f, indent=2, ensure_ascii=False)
    
    print(f"\n📊 Fixed {fixed_count} image field names")
    print(f"💾 Saved to countries_data.json")

if __name__ == '__main__':
    fix_all_image_fields()
